name: ngcomponents
version: 2.0.0-dev.2
description: Angular material components for AngularDart maintained by the community. 
repository: https://github.com/angulardart-community/angular_components

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  angular: ^7.0.1
  angular_forms: ^4.0.0
  async: ^2.1.0
  build: ^2.1.1
  build_config: ^1.0.0
  built_collection: ^5.1.1
  collection: ^1.15.0
  fixnum: ^1.0.0
  intl: ^0.17.0
  js: ^0.6.1
  logging: ^1.0.2
  meta: ^1.0.4
  observable: ^0.24.0
  protobuf: ^2.0.0
  quiver: ^3.0.1
  sass_builder: ^2.0.2

dev_dependencies:
  grinder: ^0.9.0
  lints: ^2.0.0
  path: ^1.6.1
  test: ^1.0.0
