name: angular_gallery
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ngdart: ^7.1.0
  ngcomponents: 
    path: ../ngcomponents
  ngforms: ^4.1.0
  ngrouter: ^3.1.0
  build: ^2.1.1
  build_config: ^1.0.0
  #mustache: ^1.0.0
  mustache_template: ^2.0.0
  ngsecurity:
    git: 
      url: https://github.com/angulardart-community/ngsecurity
      ref: main

