name: material_chips_example
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  angular: ^7.0.1
  ngcomponents:
    path: ../../ngcomponents
  angular_gallery:
    path: ../../angular_gallery
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: ^1.0.0

